# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import kulichtv.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kulichtv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descr', models.TextField(max_length=500)),
                ('rules', models.TextField(max_length=300)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('descr', models.TextField(max_length=275)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40)),
                ('pic', models.ImageField(default='None/none.jpg', upload_to=kulichtv.models.Profile.get_pic_url)),
            ],
        ),
        migrations.DeleteModel(
            name='SomeShit',
        ),
    ]
