# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:10
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import kulichtv.models


class Migration(migrations.Migration):

    dependencies = [
        ('kulichtv', '0005_auto_20171029_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pic',
            field=imagekit.models.fields.ProcessedImageField(upload_to=kulichtv.models.Game.get_pic_url),
        ),
    ]
