# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kulichtv', '0006_auto_20171029_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='users',
        ),
    ]
